---
title: "Using weighted survey data"
author: "Max Alletsee"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing PSM Results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
  
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

For the moment, this is a code dump with example code that was created when writing and checking the psm_analysis_weighted() function. It needs to be cleaned up at some point...

## Example Data

I will use the same set of (random) example data throughout this vignette.

```{r, echo=TRUE}
# create example data
# randomized example with gender information
# let's assume that...
# a) we have a skewed sample with only 1/3 women
# b) women are generally willing to pay +50% of the price compared to men


set.seed(20)
library(survey)

input_data <- data.frame(tch = round(rnorm(n = 250, mean = 8, sd = 1.5), digits = 2),
                         ch = round(rnorm(n = 250, mean = 12, sd = 2), digits = 2),
                         ex = round(rnorm(n = 250, mean = 13, sd = 1), digits = 2),
                         tex = round(rnorm(n = 250, mean = 15, sd = 1), digits = 2),
                         gender = sample(x = c("male", "female"), size = 250, replace = TRUE, prob = c(2/3, 1/3)))

input_data$tch[input_data$gender == "female"] <- input_data$tch[input_data$gender == "female"] * 1.5
input_data$ch[input_data$gender == "female"] <- input_data$ch[input_data$gender == "female"] * 1.5
input_data$ex[input_data$gender == "female"] <- input_data$ex[input_data$gender == "female"] * 1.5
input_data$tex[input_data$gender == "female"] <- input_data$tex[input_data$gender == "female"] * 1.5


input_data$pi_cheap <- sample(x = c(1:5), size = nrow(input_data),
                              replace = TRUE, prob = c(0.1, 0.1, 0.2, 0.3, 0.3))

input_data$pi_expensive <- sample(x = c(1:5), size = nrow(input_data),
                                  replace = TRUE, prob = c(0.3, 0.3, 0.2, 0.1, 0.1))

# now let's create a sample design object (using the survey package)
# ... assuming that gender is balanced equally in the population of 10000

input_data$gender_pop <- 5000


input_design <- survey::svydesign(ids = ~ 1, # no clusters
                          probs = NULL, # hence no cluster samling probabilities,
                          strata = input_data$gender, # stratified by gender
                          fpc = input_data$gender_pop, # strata size in the population
                          data = input_data) # data object used as input: no need to specify single variables


test <- psm_analysis_weighted(toocheap = "tch", cheap = "ch", expensive = "ex", tooexpensive = "tex", design = input_design)



```

