<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Weighted van Westendorp Price Sensitivity Meter Analysis (PSM) — psm_analysis_weighted • pricesensitivitymeter</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>

<!-- bootstrap-toc -->
<link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Weighted van Westendorp Price Sensitivity Meter Analysis (PSM) — psm_analysis_weighted" />
<meta property="og:description" content="psm_analysis_weighted() performs a weighted analysis
  of consumer price preferences and price sensitivity known as
  van Westendorp Price Sensitivity Meter (PSM). The function
  requires a sample design from the survey package as the
  main input. Custom weights or sample designs from other packages
  are not supported.
To run a PSM analysis without weighting, use the function
  psm_analysis." />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body data-spy="scroll" data-target="#toc">
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">pricesensitivitymeter</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.2.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../articles/interpolation-in-small-samples.html">Interpolation in Small Samples</a>
    </li>
    <li>
      <a href="../articles/using-weighted-data.html">Using Weighted Survey Data</a>
    </li>
    <li>
      <a href="../articles/visualizing-psm-results.html">Visualizing PSM Results</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/max-alletsee/pricesensitivitymeter/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Weighted van Westendorp Price Sensitivity Meter Analysis (PSM)</h1>
    
    <div class="hidden name"><code>psm_analysis_weighted.rd</code></div>
    </div>

    <div class="ref-description">
    <p><code>psm_analysis_weighted()</code> performs a <b>weighted</b> analysis
  of consumer price preferences and price sensitivity known as
  <b>van Westendorp Price Sensitivity Meter (PSM)</b>. The function
  requires a sample design from the <span class="pkg">survey</span> package as the
  main input. Custom weights or sample designs from other packages
  are not supported.</p>
<p>To run a PSM analysis <b>without</b> weighting, use the function
  <code><a href='psm_analysis.html'>psm_analysis</a></code>.</p>
    </div>

    <pre class="usage"><span class='fu'>psm_analysis_weighted</span><span class='op'>(</span>
  <span class='va'>toocheap</span>, <span class='va'>cheap</span>, <span class='va'>expensive</span>, <span class='va'>tooexpensive</span>,
  <span class='va'>design</span>,
  validate <span class='op'>=</span> <span class='cn'>TRUE</span>,
  interpolate <span class='op'>=</span> <span class='cn'>FALSE</span>,
  interpolation_steps <span class='op'>=</span> <span class='fl'>0.01</span>,
  intersection_method <span class='op'>=</span> <span class='st'>"min"</span>,
  pi_cheap <span class='op'>=</span> <span class='cn'>NA</span>, pi_expensive <span class='op'>=</span> <span class='cn'>NA</span>,
  pi_scale <span class='op'>=</span> <span class='fl'>5</span><span class='op'>:</span><span class='fl'>1</span>,
  pi_calibrated <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='fl'>0.7</span>, <span class='fl'>0.5</span>, <span class='fl'>0.3</span>, <span class='fl'>0.1</span>, <span class='fl'>0</span><span class='op'>)</span><span class='op'>)</span></pre>

    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>toocheap, cheap, expensive, tooexpensive</th>
      <td><p>Names
  of the variables in the data.frame/matrix that contain the
  survey data on the respondents' "too cheap", "cheap",
  "expensive" and "too expensive" price preferences.</p>
<p>If the <code>toocheap</code> price was not assessed, a
  variable of NAs can be used instead.  If <code>toocheap</code>
  is NA for all cases, it is possible to calculate the Point of
  Marginal Expensiveness and the Indifference Price Point, but it
  is impossible to calculate the Point of Marginal Cheapness and
  the Optimal Price Point.</p></td>
    </tr>
    <tr>
      <th>design</th>
      <td><p>A survey design which has been created by the
  function <code>svydesign()</code> from the <span class="pkg">survey</span>
  package. The data that is used as an input of <code>svydesign()</code>
  must include all the variable names for <code>toocheap</code>,
  <code>cheap</code>, <code>expensive</code> and <code>tooexpensive</code> variables
  specified above.</p></td>
    </tr>
    <tr>
      <th>validate</th>
      <td><p>logical. should only respondents with
  consistent price preferences (too cheap &lt; cheap &lt; expensive
  &lt; too expensive) be considered in the analysis?</p></td>
    </tr>
    <tr>
      <th>interpolate</th>
      <td><p>logical. should interpolation of the price
  curves be applied between the actual prices given by the
  respondents? If interpolation is enabled, the output appears
  less bumpy in regions with sparse price information. If the
  sample size is sufficiently large, interpolation should not
  be necessary.</p></td>
    </tr>
    <tr>
      <th>interpolation_steps</th>
      <td><p>numeric. if <code>interpolate</code> is
  <code>TRUE</code>: the size of the interpolation steps. Set by
  default to 0.01, which should be appropriate for most goods
  in a price range of 0-50 USD/Euro.</p></td>
    </tr>
    <tr>
      <th>intersection_method</th>
      <td><p>"min" (default), "max", "mean" or
  "median". defines the method how to determine the price
  points (range, indifference price, optimal price) if there
  are multiple possible intersections of the price curves.
  "min" uses the lowest possible prices, "max" uses the
  highest possible prices, "mean" calculates the mean among
  all intersections and "median" uses the median of all
  possible intersections</p></td>
    </tr>
    <tr>
      <th>pi_cheap, pi_expensive</th>
      <td><p>Only required for the Newton
  Miller Smith extension. Names of the variables in the data
  that contain the survey data on the respondents' purchase
  intent at their individual cheap/expensive price.</p></td>
    </tr>
    <tr>
      <th>pi_scale</th>
      <td><p>Only required for the Newton Miller Smith
  extension. Scale of the purchase intent variables pi_cheap and
  pi_expensive. By default assuming a five-point scale with 5
  indicating the highest purchase intent.</p></td>
    </tr>
    <tr>
      <th>pi_calibrated</th>
      <td><p>Only required for the Newton Miller Smith
  extension. Calibrated purchase probabilities that are assumed
  for each value of the purchase intent scale. Must be the same
  order as the pi_scale variable so that the first value of
  pi_calibrated corresponds to the first value in the pi_scale
  variable. Default values are taken from the Sawtooth Software
  PSM implementation in Excel: 70% for the best value of the
  purchase intent scale, 50% for the second best value,
  30% for the third best value (middle of the scale), 10%
  for the fourth best value and 0% for the worst value.</p></td>
    </tr>
    </table>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The main logic of the Price Sensitivity Meter Analysis is
explained in the documentation of the <code><a href='psm_analysis.html'>psm_analysis</a></code>
function. The <code>psm_analysis_weighted</code> performs the same
analysis, but weights the survey data according to a known
population.</p>
    <h2 class="hasAnchor" id="value"><a class="anchor" href="#value"></a>Value</h2>

    <p>The function output consists of the following elements:</p>
<p></p>
<dt><code>data_input</code>:</dt><dd><p><code>data.frame</code> object. Contains
    the data that was used as an input for the analysis.</p></dd>
    <dt><code>validated</code>:</dt><dd><p><code>logical</code> object. Indicates
    whether the <code>"validate"</code> option has been used (to
    exclude cases with intransitive price preferences).</p></dd>
    <dt><code>invalid_cases</code>:</dt><dd><p><code>numeric</code> object. Number
    of cases with intransitive price preferences.</p></dd>
    <dt><code>total_sample</code>:</dt><dd><p><code>"numeric"</code> object.
    Total sample size of the input sample <em>before</em>
    assessing the transitivity of individual price preferences.</p></dd>
    <dt><code>data_vanwestendorp</code>:</dt><dd><p><code>data.frame</code> object.
    Output data of the Price Sensitivity Meter analysis.
    Contains the <b>weighted</b> cumulative distribution
    functions for the four price assessments (too cheap, cheap,
    expensive, too expensive) for all prices.</p></dd>
    <dt><code>pricerange_lower</code>:</dt><dd><p><code>numeric</code> object. Lower
    limit of the acceptable price range as defined by the
    Price Sensitivity Meter, also known as <b>point of
    marginal cheapness</b>: Intersection of the "too cheap" and the
    "expensive" curves.</p></dd>
    <dt><code>pricerange_upper</code>:</dt><dd><p><code>numeric</code> object. Upper
    limit of the acceptable price range as defined by the Price
    Sensitivity Meter, also known as <b>point of marginal
    expensiveness</b>: Intersection of the "too expensive" and the
    "cheap" curves.</p></dd>
    <dt><code>idp</code>:</dt><dd><p><code>numeric</code> object. <b>Indifference
    Price Point</b> as defined by the Price Sensitivity Meter:
    Intersection of the "cheap" and the "expensive" curves.</p></dd>
    <dt><code>opp</code>:</dt><dd><p><code>numeric</code> object. <b>Optimal
    Price Point</b> as defined by the Price Sensitivity Meter:
    Intersection of the "too cheap" and the "too expensive"
    curves.</p></dd>
    <dt><code>weighted</code>:</dt><dd><p><code>logical</code> object. Indicating
    if weighted data was used in the analysis. Outputs from
    <code>psm_analysis_weighted()</code> always have the value
    <code>TRUE</code>. When data is unweighted, use the function
    <code><a href='psm_analysis.html'>psm_analysis</a>.</code></p></dd>
    <dt><code>survey_design</code>:</dt><dd><p><code>survey.design2</code> object.
    Returning the full survey design as specified with the
    <code><a href='https://rdrr.io/pkg/survey/man/svydesign.html'>svydesign</a></code> function from the <span class="pkg">survey</span> package.</p></dd>
    <dt><code>NMS</code>:</dt><dd><p><code>logical</code> object. Indicates whether
    the additional analyses of the Newton Miller Smith Extension
    were performed.</p></dd>

    <h2 class="hasAnchor" id="references"><a class="anchor" href="#references"></a>References</h2>

    <p>Van Westendorp, P (1976) "NSS-Price Sensitivity Meter (PSM) --
  A new approach to study consumer perception of price"
  <em>Proceedings of the ESOMAR 29th Congress</em>, 139--167. Online
  available at <a href='https://www.researchworld.com/a-new-approach-to-study-consumer-perception-of-price/'>https://www.researchworld.com/a-new-approach-to-study-consumer-perception-of-price/</a>.</p>
<p>Newton, D, Miller, J, Smith, P, (1993) "A market acceptance
  extension to traditional price sensitivity measurement"
  <em>Proceedings of the American Marketing Association
  Advanced Research Techniques Forum</em>.</p>
<p>Sawtooth Software (2016) "Templates for van Westendorp PSM for
  Lighthouse Studio and Excel". Online available at
  <a href='https://sawtoothsoftware.com/resources/software-downloads/tools/van-westendorp-price-sensitivity-meter'>https://sawtoothsoftware.com/resources/software-downloads/tools/van-westendorp-price-sensitivity-meter</a></p>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'>
<span class='co'># assuming a skewed sample with only 1/3 women and 2/3 men</span>

<span class='va'>input_data</span> <span class='op'>&lt;-</span> <span class='fu'><a href='https://rdrr.io/r/base/data.frame.html'>data.frame</a></span><span class='op'>(</span>tch <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/Round.html'>round</a></span><span class='op'>(</span><span class='fu'><a href='https://rdrr.io/r/stats/Normal.html'>rnorm</a></span><span class='op'>(</span>n <span class='op'>=</span> <span class='fl'>250</span>, mean <span class='op'>=</span> <span class='fl'>8</span>, sd <span class='op'>=</span> <span class='fl'>1.5</span><span class='op'>)</span>, digits <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>,
                         ch <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/Round.html'>round</a></span><span class='op'>(</span><span class='fu'><a href='https://rdrr.io/r/stats/Normal.html'>rnorm</a></span><span class='op'>(</span>n <span class='op'>=</span> <span class='fl'>250</span>, mean <span class='op'>=</span> <span class='fl'>12</span>, sd <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>, digits <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>,
                         ex <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/Round.html'>round</a></span><span class='op'>(</span><span class='fu'><a href='https://rdrr.io/r/stats/Normal.html'>rnorm</a></span><span class='op'>(</span>n <span class='op'>=</span> <span class='fl'>250</span>, mean <span class='op'>=</span> <span class='fl'>13</span>, sd <span class='op'>=</span> <span class='fl'>1</span><span class='op'>)</span>, digits <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>,
                         tex <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/Round.html'>round</a></span><span class='op'>(</span><span class='fu'><a href='https://rdrr.io/r/stats/Normal.html'>rnorm</a></span><span class='op'>(</span>n <span class='op'>=</span> <span class='fl'>250</span>, mean <span class='op'>=</span> <span class='fl'>15</span>, sd <span class='op'>=</span> <span class='fl'>1</span><span class='op'>)</span>, digits <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>,
                         gender <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/sample.html'>sample</a></span><span class='op'>(</span>x <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='st'>"male"</span>, <span class='st'>"female"</span><span class='op'>)</span>,
                                         size <span class='op'>=</span> <span class='fl'>250</span>,
                                         replace <span class='op'>=</span> <span class='cn'>TRUE</span>,
                                         prob <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='fl'>2</span><span class='op'>/</span><span class='fl'>3</span>, <span class='fl'>1</span><span class='op'>/</span><span class='fl'>3</span><span class='op'>)</span><span class='op'>)</span><span class='op'>)</span>

<span class='co'># ... and in which women have on average 1.5x the price acceptance of men</span>
<span class='va'>input_data</span><span class='op'>$</span><span class='va'>tch</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>&lt;-</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>tch</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>*</span> <span class='fl'>1.5</span>
<span class='va'>input_data</span><span class='op'>$</span><span class='va'>ch</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>&lt;-</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>ch</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>*</span> <span class='fl'>1.5</span>
<span class='va'>input_data</span><span class='op'>$</span><span class='va'>ex</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>&lt;-</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>ex</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>*</span> <span class='fl'>1.5</span>
<span class='va'>input_data</span><span class='op'>$</span><span class='va'>tex</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>&lt;-</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>tex</span><span class='op'>[</span><span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span> <span class='op'>==</span> <span class='st'>"female"</span><span class='op'>]</span> <span class='op'>*</span> <span class='fl'>1.5</span>

<span class='co'># creating a sample design object using the survey package</span>
<span class='co'># ... assuming that gender is balanced equally in the population of 10000</span>

<span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender_pop</span> <span class='op'>&lt;-</span> <span class='fl'>5000</span>

<span class='va'>input_design</span> <span class='op'>&lt;-</span> <span class='fu'>survey</span><span class='fu'>::</span><span class='fu'><a href='https://rdrr.io/pkg/survey/man/svydesign.html'>svydesign</a></span><span class='op'>(</span>ids <span class='op'>=</span> <span class='op'>~</span> <span class='fl'>1</span>, <span class='co'># no clusters</span>
                          probs <span class='op'>=</span> <span class='cn'>NULL</span>, <span class='co'># hence no cluster samling probabilities,</span>
                          strata <span class='op'>=</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender</span>, <span class='co'># stratified by gender</span>
                          fpc <span class='op'>=</span> <span class='va'>input_data</span><span class='op'>$</span><span class='va'>gender_pop</span>, <span class='co'># strata size in the population</span>
                          data <span class='op'>=</span> <span class='va'>input_data</span><span class='op'>)</span>
                          <span class='co'># data object used as input: no need to specify single variables</span>


<span class='va'>output_weighted_psm</span> <span class='op'>&lt;-</span> <span class='fu'>psm_analysis_weighted</span><span class='op'>(</span>toocheap <span class='op'>=</span> <span class='st'>"tch"</span>,
  cheap <span class='op'>=</span> <span class='st'>"ch"</span>,
  expensive <span class='op'>=</span> <span class='st'>"ex"</span>,
  tooexpensive <span class='op'>=</span> <span class='st'>"tex"</span>,
  design <span class='op'>=</span> <span class='va'>input_design</span><span class='op'>)</span>

<span class='fu'><a href='https://rdrr.io/r/base/summary.html'>summary</a></span><span class='op'>(</span><span class='va'>output_weighted_psm</span><span class='op'>)</span>
</div><div class='output co'>#&gt; Van Westendorp Price Sensitivity Meter Analysis
#&gt; 
#&gt; Accepted Price Range: 11.6 - 17.34 
#&gt; Indifference Price Point: 14.72 
#&gt; Optimal Price Point: 14.22 
#&gt; 
#&gt; ---
#&gt; 125 cases with individual price preferences were analyzed (weighted data).
#&gt; Total data set consists of 250 cases. Analysis was limited to cases with transitive price preferences.
#&gt; (Removed: n = 125 / 50% of data)</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <nav id="toc" data-toggle="toc" class="sticky-top">
      <h2 data-toc-skip>Contents</h2>
    </nav>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Max Alletsee.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


